<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Kompas" name="ProdTest" tests="5" failures="1" timestamp="17 Jun 2015 17:42:36 GMT" time="499.868" errors="0">
  <testcase name="testLogin" time="10.534" classname="test.java.CloudTest.NewTest"/>
  <testcase name="testDeleteDevice" time="9.277" classname="test.java.CloudTest.NewTest"/>
  <testcase name="testAddDevice" time="249.235" classname="test.java.CloudTest.NewTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at test.java.CloudTest.NewTest.testAddDevice(NewTest.java:161)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testAddDevice -->
  <testcase name="testControl" time="90.182" classname="test.java.CloudTest.NewTest"/>
  <testcase name="testLogout" time="30.589" classname="test.java.CloudTest.NewTest"/>
</testsuite> <!-- ProdTest -->
