<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Kompas" name="ProdTest" tests="5" failures="2" timestamp="14 Jun 2015 19:36:17 GMT" time="544.497" errors="0">
  <testcase name="testLogin" time="11.27" classname="test.java.CloudTest.NewTest"/>
  <testcase name="testDeleteDevice" time="8.989" classname="test.java.CloudTest.NewTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at test.java.CloudTest.NewTest.testDeleteDevice(NewTest.java:217)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteDevice -->
  <testcase name="testAddDevice" time="104.042" classname="test.java.CloudTest.NewTest"/>
  <testcase name="testLogout" time="9.027" classname="test.java.CloudTest.NewTest"/>
  <testcase name="testControl" time="316.122" classname="test.java.CloudTest.NewTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at test.java.CloudTest.tests.Control.outputControl(Control.java:147)
	at test.java.CloudTest.tests.Control.execute(Control.java:64)
	at test.java.CloudTest.NewTest.testControl(NewTest.java:270)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testControl -->
</testsuite> <!-- ProdTest -->
